platform :ios, '8.0'

inhibit_all_warnings!

target 'WJCycleViewExample' do
  pod 'WJCycleView', :path => "../"
  pod 'AFNetworking'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
    end
  end
end

